# Generated by Django 5.1.3 on 2026-05-15 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_mh', models.CharField(max_length=20, unique=True, verbose_name='Mã môn học')),
                ('ten_mh', models.CharField(max_length=200, verbose_name='Tên môn học')),
                ('so_tc', models.PositiveSmallIntegerField(verbose_name='Số tín chỉ')),
                ('loai', models.CharField(choices=[('bat_buoc', 'Bắt buộc'), ('tu_chon', 'Tự chọn'), ('dai_cuong', 'Đại cương'), ('chuyen_nganh', 'Chuyên ngành')], default='bat_buoc', max_length=20, verbose_name='Loại học phần')),
                ('mo_ta', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Môn học',
                'verbose_name_plural': 'Môn học',
                'ordering': ['ma_mh'],
            },
        ),
        migrations.CreateModel(
            name='Nganh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nganh', models.CharField(max_length=20, unique=True, verbose_name='Mã ngành')),
                ('ten_nganh', models.CharField(max_length=200, verbose_name='Tên ngành')),
            ],
            options={
                'verbose_name': 'Ngành học',
                'verbose_name_plural': 'Ngành học',
            },
        ),
        migrations.CreateModel(
            name='HocKy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ky', models.CharField(choices=[('1', 'Học kỳ 1'), ('2', 'Học kỳ 2'), ('3', 'Học kỳ hè')], max_length=2, verbose_name='Kỳ học')),
                ('nam_hoc', models.CharField(help_text='VD: 2023-2024', max_length=10, verbose_name='Năm học')),
                ('ngay_bat_dau', models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu')),
                ('ngay_ket_thuc', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('la_hien_tai', models.BooleanField(default=False, verbose_name='Học kỳ hiện tại')),
            ],
            options={
                'verbose_name': 'Học kỳ',
                'verbose_name_plural': 'Học kỳ',
                'ordering': ['-nam_hoc', '-ky'],
                'unique_together': {('ky', 'nam_hoc')},
            },
        ),
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mssv', models.CharField(max_length=20, unique=True, verbose_name='Mã số sinh viên')),
                ('ho_ten', models.CharField(max_length=200, verbose_name='Họ và tên')),
                ('ngay_sinh', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gioi_tinh', models.CharField(blank=True, choices=[('Nam', 'Nam'), ('Nu', 'Nữ')], max_length=5)),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('so_dien_thoai', models.CharField(blank=True, max_length=15, verbose_name='Số điện thoại')),
                ('khoa', models.CharField(help_text='VD: K2021', max_length=10, verbose_name='Khóa học')),
                ('lop', models.CharField(blank=True, max_length=50, verbose_name='Lớp')),
                ('trang_thai', models.CharField(choices=[('dang_hoc', 'Đang học'), ('canh_bao', 'Cảnh báo học vụ'), ('dinh_chi', 'Đình chỉ'), ('tot_nghiep', 'Tốt nghiệp'), ('thoi_hoc', 'Thôi học')], default='dang_hoc', max_length=20, verbose_name='Trạng thái')),
                ('ngay_nhap_hoc', models.DateField(blank=True, null=True, verbose_name='Ngày nhập học')),
                ('covan', models.ForeignKey(blank=True, limit_choices_to={'role': 'covan'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sinh_vien_phu_trach', to=settings.AUTH_USER_MODEL, verbose_name='Cố vấn học tập')),
                ('nganh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.nganh', verbose_name='Ngành')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sinh_vien', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Sinh viên',
                'verbose_name_plural': 'Sinh viên',
                'ordering': ['mssv'],
            },
        ),
    ]
