# Generated by Django 5.1.3 on 2026-05-18 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_lop', models.CharField(max_length=50, unique=True, verbose_name='Tên lớp')),
                ('khoa', models.CharField(help_text='VD: K2021', max_length=10, verbose_name='Khóa học')),
                ('covan', models.OneToOneField(blank=True, limit_choices_to={'role': 'covan'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lop_phu_trach', to=settings.AUTH_USER_MODEL, verbose_name='Cố vấn học tập')),
                ('nganh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.nganh', verbose_name='Ngành')),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': 'Lớp học',
                'ordering': ['ten_lop'],
            },
        ),
        migrations.AlterField(
            model_name='sinhvien',
            name='lop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sinh_viens', to='students.lop', verbose_name='Lớp'),
        ),
    ]
