# Generated by Django 5.1.3 on 2026-06-07 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_nganh_khoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='monhoc',
            name='hoc_ky_ctdt',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Học kỳ (CTĐT)'),
        ),
        migrations.AddField(
            model_name='monhoc',
            name='nam_hoc_ctdt',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Năm học (CTĐT)'),
        ),
        migrations.AddField(
            model_name='monhoc',
            name='nganh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mon_hocs', to='students.nganh', verbose_name='Chương trình đào tạo'),
        ),
    ]
