# Generated by Django 5.1.3 on 2026-06-21 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_monhoc_hoc_ky_ctdt_monhoc_nam_hoc_ctdt_monhoc_nganh'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hocky',
            table='hocky',
        ),
        migrations.AlterModelTable(
            name='lop',
            table='lop',
        ),
        migrations.AlterModelTable(
            name='monhoc',
            table='monhoc',
        ),
        migrations.AlterModelTable(
            name='nganh',
            table='nganh',
        ),
        migrations.AlterModelTable(
            name='sinhvien',
            table='sinhvien',
        ),
    ]
