# Generated by Django 5.1.3 on 2026-07-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_hocky_table_alter_lop_table_alter_monhoc_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinhvien',
            name='trang_thai',
            field=models.CharField(choices=[('dang_hoc', 'Đang học'), ('dinh_chi', 'Đình chỉ'), ('tot_nghiep', 'Tốt nghiệp'), ('thoi_hoc', 'Thôi học')], default='dang_hoc', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
