# Generated by Django 5.1.3 on 2026-05-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_lop_alter_sinhvien_lop'),
    ]

    operations = [
        migrations.AddField(
            model_name='nganh',
            name='khoa',
            field=models.CharField(default='Khoa Công nghệ thông tin', max_length=200, verbose_name='Khoa'),
        ),
    ]
