# Generated by Django 5.1.3 on 2026-05-15 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_warnings', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canhbaohocvu',
            name='hoc_ky',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canh_bao', to='students.hocky', verbose_name='Học kỳ'),
        ),
        migrations.AddField(
            model_name='canhbaohocvu',
            name='sinh_vien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canh_bao', to='students.sinhvien', verbose_name='Sinh viên'),
        ),
        migrations.AlterUniqueTogether(
            name='canhbaohocvu',
            unique_together={('sinh_vien', 'hoc_ky')},
        ),
    ]
