# Generated by Django 5.1.3 on 2026-05-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_warnings', '0003_canhbaohocvu_so_lan_canh_bao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='canhbaohocvu',
            name='da_an',
            field=models.BooleanField(default=False, verbose_name='Đã ẩn khỏi danh sách'),
        ),
        migrations.AlterField(
            model_name='canhbaohocvu',
            name='trang_thai',
            field=models.CharField(choices=[('chua_xu_ly', 'Chưa xử lý'), ('da_xu_ly', 'Đã xử lý')], default='chua_xu_ly', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
