# Generated by Django 5.1.3 on 2026-06-01 00:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_warnings', '0004_canhbaohocvu_da_an_alter_canhbaohocvu_trang_thai'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='canhbaohocvu',
            name='nguoi_dung_an',
            field=models.ManyToManyField(blank=True, related_name='canh_bao_da_an', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng đã ẩn'),
        ),
    ]
