# Generated by Django 5.1.3 on 2026-06-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_warnings', '0005_canhbaohocvu_nguoi_dung_an'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canhbaohocvu',
            name='trang_thai',
            field=models.CharField(choices=[('chua_xu_ly', 'Chưa thông báo'), ('da_xu_ly', 'Đã thông báo')], default='chua_xu_ly', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
