# Generated by Django 5.1.3 on 2026-06-21 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_warnings', '0008_alter_canhbaohocvu_options_lichsuguicanhbaosom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='canhbaohocvu',
            name='nguoi_dung_an',
            field=models.ManyToManyField(blank=True, db_table='canhbaohocvu_nguoi_dung_an', related_name='canh_bao_da_an', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng đã ẩn'),
        ),
        migrations.AlterModelTable(
            name='canhbaohocvu',
            table='canhbaohocvu',
        ),
        migrations.AlterModelTable(
            name='lichsuguicanhbaosom',
            table='lichsuguicanhbaosom',
        ),
        migrations.AlterModelTable(
            name='lichsuguiemailbaocao',
            table='lichsuguiemailbaocao',
        ),
    ]
