# Generated by Django 5.1.3 on 2026-05-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanhBaoHocVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muc_canh_bao', models.CharField(choices=[('muc1', 'Cảnh báo mức 1'), ('muc2', 'Cảnh báo mức 2'), ('muc3', 'Cảnh báo mức 3 (Buộc thôi học)')], max_length=10, verbose_name='Mức cảnh báo')),
                ('ly_do', models.TextField(verbose_name='Lý do cảnh báo')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('trang_thai', models.CharField(choices=[('moi', 'Mới'), ('da_thong_bao', 'Đã thông báo'), ('dang_xu_ly', 'Đang xử lý'), ('da_xu_ly', 'Đã xử lý')], default='moi', max_length=20, verbose_name='Trạng thái')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú xử lý')),
            ],
            options={
                'verbose_name': 'Cảnh báo học vụ',
                'verbose_name_plural': 'Cảnh báo học vụ',
                'ordering': ['-ngay_tao'],
            },
        ),
    ]
