# Generated by Django 5.1.3 on 2026-05-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_warnings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canhbaohocvu',
            name='so_lan_canh_bao',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Lần cảnh báo thứ'),
        ),
        migrations.AlterField(
            model_name='canhbaohocvu',
            name='muc_canh_bao',
            field=models.CharField(choices=[('canh_bao', 'Cảnh báo học vụ'), ('buoc_thoi_hoc', 'Buộc thôi học')], max_length=20, verbose_name='Mức cảnh báo'),
        ),
    ]
