# Generated by Django 5.1.3 on 2026-06-07 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_warnings', '0006_alter_canhbaohocvu_trang_thai'),
        ('students', '0004_monhoc_hoc_ky_ctdt_monhoc_nam_hoc_ctdt_monhoc_nganh'),
    ]

    operations = [
        migrations.CreateModel(
            name='LichSuGuiEmailBaoCao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_gui', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi')),
                ('hoc_ky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.hocky', verbose_name='Học kỳ báo cáo')),
                ('lop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.lop', verbose_name='Lớp')),
            ],
            options={
                'verbose_name': 'Lịch sử gửi báo cáo lớp',
                'verbose_name_plural': 'Lịch sử gửi báo cáo lớp',
                'unique_together': {('lop', 'hoc_ky')},
            },
        ),
    ]
