# Generated by Django 5.1.3 on 2026-06-18 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_warnings', '0007_lichsuguiemailbaocao'),
        ('students', '0004_monhoc_hoc_ky_ctdt_monhoc_nam_hoc_ctdt_monhoc_nganh'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canhbaohocvu',
            options={'ordering': ['trang_thai', '-ngay_tao'], 'verbose_name': 'Cảnh báo học vụ', 'verbose_name_plural': 'Cảnh báo học vụ'},
        ),
        migrations.CreateModel(
            name='LichSuGuiCanhBaoSom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_gui', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi')),
                ('muc_nguy_co', models.CharField(max_length=50, verbose_name='Mức nguy cơ')),
                ('gpa_he4', models.FloatField(verbose_name='GPA tích lũy hệ 4')),
                ('hoc_ky', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_gui_canh_bao_som', to='students.hocky', verbose_name='Học kỳ')),
                ('sinh_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_gui_canh_bao_som', to='students.sinhvien', verbose_name='Sinh viên')),
            ],
            options={
                'verbose_name': 'Lịch sử gửi cảnh báo sớm',
                'verbose_name_plural': 'Lịch sử gửi cảnh báo sớm',
                'ordering': ['-ngay_gui'],
            },
        ),
    ]
